name: deploy docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Clean install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Build docs
        run: pnpm run build:docs

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
