name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
      - name: Clean install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Check project can build successfully
        run: pnpm run build
      - name: Check project linting
        run: pnpm run lint:check
