name: Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Clean install npm dependencies
        run: npm ci
      - name: Check project can build successfully
        run: npm run build
      - name: Check project linting
        run: npm run lint:check
      - name: Run unit tests
        run: npm run test
      - name: Deploy docs
        run: git-branch-is master && push-dir --dir=docs --branch=gh-pages --cleanup