name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Clean install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Check project can build successfully
        run: pnpm run build

      - name: Check docs can build successfully
        run: pnpm run build:docs

      - name: Check project linting
        run: pnpm run lint:check

      - name: Run unit test
        run: pnpm run test

      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          fail_ci_if_error: true
          verbose: true
